CREATE TABLE [dbo].[Audience](
	[ClientID] [varchar](32) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Secret] [varchar](80) NOT NULL,
	[Issuer] [varchar](150) NULL,
 CONSTRAINT [PK_Audience] PRIMARY KEY CLUSTERED 
(
	[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO